### ISSUE TITLE
Commands 35 in Conditions and commands data mapping

### ISSUE THREAD

**Issue by auraes** [pdxiv/PerlScott#1]
There seems to be a small error in your Conditions and commands data mapping:
the Commands 35 seem to be EXc,CR (current room) and not 35 EXc,CT (counter)
EXc,CR: "Exchange current room with room in alternate room register C."

**Comment by pdxiv** [comment]
Thank you for the report! This needs to be corrected. The root cause for this is in my transcription of Alan Moluf's document "The Adventure Data Base Format" from 1980. Not sure if this was a typo in the original, or my transcription of it:
https://github.com/pdxiv/LuaScott/blob/master/doc/The_ADVENTURE_Data_Base_Format_(1980).md

The other document i used as reference "Adventure Editor Manual", has this entered correctly:
https://github.com/pdxiv/LuaScott/blob/master/doc/Adventure_Editor_Manual_(1981).md

**Comment by auraes** [comment]
The error appears in the text file ADVDB.TXT and there is also information in the ADV.HLP text file:
http://willus.com/trs80/?q=Molluf

But I prefer to use this document (I did not know your transcription):
https://mocagh.org/loadpage.php?getgame=advsystem

**Comment by pdxiv** [comment]
The files `conditions_and_commands_data_mapping.md` and `perlscott.pl` have been updated: https://github.com/pdxiv/PerlScott/commit/4257eb113d0f43a3886686059f933abed9b43561

Thank you again for your contribution!
