### ISSUE TITLE
Abbreviations for directions, look and inventory

### ISSUE THREAD

**Issue by heasm66** [pdxiv/PerlScott#15]
You might consider implementing the on letter abbreviations for directions, inventory and look. It probably wasn't in the 4.6 release but it's quite tedious to type "GO" before efery direction. I tried the following code on line 624-
```
	if ( length( $keyboard_input_2 ) == 1 ) {
		if ( lc( $keyboard_input_2 ) eq "n" ) { $keyboard_input_2 = "go north" };
		if ( lc( $keyboard_input_2 ) eq "s" ) { $keyboard_input_2 = "go south" };
		if ( lc( $keyboard_input_2 ) eq "e" ) { $keyboard_input_2 = "go east" };
		if ( lc( $keyboard_input_2 ) eq "w" ) { $keyboard_input_2 = "go west" };
		if ( lc( $keyboard_input_2 ) eq "u" ) { $keyboard_input_2 = "go up" };
		if ( lc( $keyboard_input_2 ) eq "d" ) { $keyboard_input_2 = "go down" };
		if ( lc( $keyboard_input_2 ) eq "o" ) { $keyboard_input_2 = "go out" };
		if ( lc( $keyboard_input_2 ) eq "i" ) { $keyboard_input_2 = "inventory" };
		if ( lc( $keyboard_input_2 ) eq "l" ) { $keyboard_input_2 = "look" };
	};
```
There probably is a more elegant way to do this in perl (regexp?) but this worked.

**Comment by pdxiv** [comment]
@heasm66 Thanks for this suggestion. I've thought about this for a (very) long time now, and your solution is valid, and probably true to how it was implemented back in the day. My problem with this very practical approach, is that it would mean hard-coding for a specific language (English). The interpreter *is* pretty much hard-coded to English already, but I wouldn't want to take that any further. If anything I would like to try to make it multilingual-capable some day.

What I would like to do instead, is to try to infer verbs and nouns from unique partial spelling, similar to how the DCL commandline in OpenVMS acted. There, if you entered `DIR`, it would infer that you meant the `DIRECTORY` command. If you just entered `DI` it would bite back with: `%DCL-W-ABVERB, ambiguous command verb - supply more characters      \DI\` since it wasn't able to differentiate the `DIRECTORY` command from the `DISCONNECT` command. I guess it was like an early form of "tab completion".

The cardinal direction "nouns" have a special standing in Scott Adams games, as do the GET/DROP verbs. That makes them relatively easy to abbreviate in this way.

Verbs and nouns referring to actions (like "inventory" and "look") are less obvious. You would *probably* need to evaluate the condition blocks of all the "verb/noun actions" actions first, to see which ones are possible to execute, see what verbs and nouns they have and figure out if what was entered was unambiguous - and to see that it doesn't clash with GET/DROP.

I totally want to do this, but I *think* this as close as I can come to figure out how to go about doing it. Maybe I'm overthinking this, and if so, I wouldn't mind being set straight on the matter. 🙂

**Comment by heasm66** [comment]
I think your approach is sensible. The directions are the most used commands and also quickly becomes the most tedious commands to type from a players perspective.

Anecdotaly I patched the 77, 78 & 79 versions of Zork (the mainframe version) earlier this year to make them runnable inside Confusion (partial MDL interpreter for modern computers). All the versions have abbreviations for the directions and for "look" but "i" for inventory is introduced in the 79 version. So to only have abbreviations for the directions certainly is in the zeitgeist of the time period.

**Comment by pdxiv** [comment]
I implemented resolution of "shortcuts" for walking in the cardinal directions in commit 1511b4c77bd7afd32ee31577c4c7696b4caed539
I won't implement shortcuts for `inventory` and `look`, since that would require a lot of work to do in a language-neutral way, with relatively little benefit. If someone feels the urge to do that, I *do* accept pull requests :smiley:
